[MPIPreferences]
__clear__ = ["preloads_env_switch"]
_format = "1.0"
abi = "OpenMPI"
binary = "system"
cclibs = []
libmpi = "/fs1/local/cluster/CEOAS/spack/opt/spack/linux-rocky9-sandybridge/gcc-13.2.0/openmpi-4.1.6-ix6ituu3kr26freyez7y4k6aorb4q7nn/lib/libmpi.so"
mpiexec = "/fs1/local/cluster/CEOAS/spack/opt/spack/linux-rocky9-sandybridge/gcc-13.2.0/openmpi-4.1.6-ix6ituu3kr26freyez7y4k6aorb4q7nn/bin/mpiexec"
preloads = []
