[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
HDF5_jll = "0234f1f7-429e-5d53-9886-15a909be8d59"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
LanguageServer = "2b0e0bc5-e4fd-59b4-8912-456d1b03d8d7"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
OpenMPI_jll = "fe0851c0-eecd-5654-98d4-656369965a5c"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
OpenMPI_jll = "^4"
